version: '2'
services:
  r8meuserservice2-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/r8meuserservice2/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=r8meuserservice2
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
